// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// ignore: unused_import
import 'firebase_options_dev.dart'
    if (dart.library.io) 'firebase_options_prod.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcVoLDVvp2xaTW-SFRIrquvuMYt4eG7BY',
    appId: '1:108723258802:web:90dc488f012c75872cd0ab',
    messagingSenderId: '108723258802',
    projectId: 'score-cb1bd',
    authDomain: 'score-cb1bd.firebaseapp.com',
    storageBucket: 'score-cb1bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvP1c85rAThfv6p4Jo7lZapzKjGVwsvks',
    appId: '1:108723258802:android:48f4603210125a592cd0ab',
    messagingSenderId: '108723258802',
    projectId: 'score-cb1bd',
    storageBucket: 'score-cb1bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmvAKJ9RZoHtoDzMN6-YKfiUpfQYuQAQY',
    appId: '1:108723258802:ios:83cba604eef3f9002cd0ab',
    messagingSenderId: '108723258802',
    projectId: 'score-cb1bd',
    storageBucket: 'score-cb1bd.firebasestorage.app',
    iosBundleId: 'com.example.fluttergameIc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmvAKJ9RZoHtoDzMN6-YKfiUpfQYuQAQY',
    appId: '1:108723258802:ios:83cba604eef3f9002cd0ab',
    messagingSenderId: '108723258802',
    projectId: 'score-cb1bd',
    storageBucket: 'score-cb1bd.firebasestorage.app',
    iosBundleId: 'com.example.fluttergameIc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcVoLDVvp2xaTW-SFRIrquvuMYt4eG7BY',
    appId: '1:108723258802:web:bf9d8f802c8833142cd0ab',
    messagingSenderId: '108723258802',
    projectId: 'score-cb1bd',
    authDomain: 'score-cb1bd.firebaseapp.com',
    storageBucket: 'score-cb1bd.firebasestorage.app',
  );
}
